Headers
hellosign/hellosign-ruby-sdk pull request #82
Opened 2018-04-25 23:09 UTC by jyoung488

2018-04-26 23:30 UTC, jyoung488 commented
Addresses #38

2018-04-30 15:17 UTC, michaelnlindsay requested changes

2018-04-30 15:17 UTC, michaelnlindsay commented on lib/hello_sign/version.rb
> -  VERSION = '3.6.4'
3.7.0 for proper symantic versioning

2018-04-30 15:17 UTC, michaelnlindsay commented on lib/hello_sign/resource/base_resource.rb
> +        @warnings = hash['warnings'] ? hash[:body]['warnings'] : nil
Shouldn't this be: 
@warnings = hash**[:body]**['warnings'] ? hash[:body]['warnings'] : nil

2018-04-30 15:17 UTC, michaelnlindsay commented on lib/hello_sign/resource/base_resource.rb
> +        @warnings = hash['warnings'] ? hash[:body]['warnings'] : nil
may want to add a test for warnings as well

2018-07-12 22:55 UTC, jyoung488 commented
@michaelnlindsay I finally got around to implementing this! Would you mind reviewing again for the headers and warnings?

2018-07-13 21:18 UTC, michaelnlindsay approved these changes
looks great!

2018-07-13 21:27 UTC, merged